trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout code from GitHub'

- script: |
    echo "##vso[task.setvariable variable=tag]9.0"
  displayName: 'Generate unique tag'

- task: Docker@2
  displayName: 'Docker Login to Quay.io'
  inputs:
    command: 'login'
    containerRegistry: 'quayRegistry'
    username: 'perzam'
    password: 's0p0rt3.P3rZ4m.&2'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: 'quayRegistry'
    repository: 'perzam/ocp-app'
    dockerfile: 'Dockerfile'
    tags: |
      $(tag)

- task: Docker@2
  displayName: 'Push Docker image to Quay.io'
  inputs:
    command: 'push'
    containerRegistry: 'quayRegistry'
    repository: 'perzam/ocp-app'
    tags: |
      $(tag)



